"use strict";
class TelaOnline {
  constructor(app){this.app=app;this.save=app.save;this.status="Crie uma sala ou entre com um código";this.codigo="";this.host=false;this.resumo=null;this.botoes=[];}
  entrar(){this.app.sound.startMusic("menu_music");}
  sair(){if(!OnlineSession.enabled)OnlineSession.service?.close();}
  update(){}
  medir(){}
  conectar(criar){const digitado=criar?"":String(prompt("Código da sala:",this.codigo)||"").trim().toUpperCase();if(!criar&&!digitado)return;this.status="Conectando ao servidor…";const service=new OnlineService(this.save.onlineServerUrl);OnlineSession.service=service;OnlineSession.isHost=criar;OnlineSession.enabled=false;service.setListener({onStatus:m=>this.status=m,onConnected:()=>{},onDisconnected:m=>this.status=m,onRawMessage:()=>{},onStateReceived:()=>{},onRoomUpdate:r=>{this.resumo=r;this.codigo=r.id||this.codigo;this.host=r.anfitriaoPid===service.pid;this.status="Sala pronta — compartilhe o código";},onRaceStart:r=>{OnlineSession.enabled=true;OnlineSession.stageIndex=r.fase;const esperaSincronizada=Math.max(0,(r.emMs||0)-(service.latenciaMs||0)/2);this.app.irPara("corrida",{stageIndex:r.fase,semente:r.semente,esperaLargadaMs:esperaSincronizada});}});service.conectar({criar:criar,sala:digitado,nome:this.save.playerName,carId:this.save.selectedCarId,max:4,fase:0});}
  render(ctx,w,h){const g=ctx.createLinearGradient(0,0,w,h);g.addColorStop(0,"#07152f");g.addColorStop(1,"#27062f");ctx.fillStyle=g;ctx.fillRect(0,0,w,h);ctx.textAlign="center";ctx.font=`900 ${Math.max(28,h*.10)}px ${FONTE}`;ctx.fillStyle="#39efff";ctx.fillText("SALA ONLINE",w/2,h*.16);ctx.font=`700 ${Math.max(15,h*.035)}px ${FONTE}`;ctx.fillStyle="#fff";ctx.fillText(this.codigo?"CÓDIGO: "+this.codigo:this.status,w/2,h*.27);const labels=this.codigo?["PRONTO","INICIAR CORRIDA","VOLTAR"]:["CRIAR SALA","ENTRAR NA SALA","VOLTAR"];this.botoes=[];labels.forEach((t,i)=>{const r={left:w*.28,right:w*.72,top:h*(.38+i*.16),bottom:h*(.49+i*.16)};this.botoes.push(r);const grad=ctx.createLinearGradient(r.left,0,r.right,0);grad.addColorStop(0,i===1?"#fe2d9b":"#196dff");grad.addColorStop(1,"#632cff");ctx.fillStyle=grad;retanguloArredondado(ctx,r,18);ctx.fill();ctx.strokeStyle="#63f6ff";ctx.lineWidth=2;ctx.stroke();ctx.fillStyle="#fff";ctx.font=`800 ${Math.max(14,h*.035)}px ${FONTE}`;ctx.fillText(t,w/2,(r.top+r.bottom)/2+h*.012);});if(this.resumo?.jogadores){ctx.font=`600 ${Math.max(12,h*.025)}px ${FONTE}`;ctx.fillText(this.resumo.jogadores.map(p=>p.nome+(p.pronto?" ✓":"")).join("  •  "),w/2,h*.91);}}
  aoApontar(tipo,x,y){if(tipo!=="cima")return;const i=this.botoes.findIndex(r=>Ret.contem(r,x,y));if(i<0)return;if(!this.codigo){if(i===0)this.conectar(true);else if(i===1)this.conectar(false);else this.app.irPara("menu");}else{if(i===0)OnlineSession.service?.setReady(true);else if(i===1){if(this.host)OnlineSession.service?.startRace();else this.status="Somente o anfitrião pode iniciar";}else{OnlineSession.clear();this.app.irPara("menu");}}}
}
window.TelaOnline=TelaOnline;
